### ISSUE TITLE
private function

### ISSUE THREAD

**Issue by Ogimle** [wavesplatform/waves-api#30]
from rest API
> All private functions below require API Key to be provided in every HTTP request using X-Api-Key header.

how to setup node module for it?

**Comment by xenohunter** [comment]
Hello! Sorry for the long delay. I guess [that would be a good place](https://github.com/wavesplatform/Waves/wiki) to start. If you still have questions, the [wavesplatform/Waves](https://github.com/wavesplatform/Waves) repository will be a better place to ask about it.
