### ISSUE TITLE
fetchSubstitute leads to fatal error while waves-api executes in NodeJS's WebWorkers emulated environment

### ISSUE THREAD

**Issue by dananichev** [wavesplatform/waves-api#34]
F.e. create a worker with https://github.com/avoidwork/tiny-worker and try to use ``waves-api`` inside this worker. 

The problem related to ``fetchSubstitute``:
```javascript
    if (typeof window !== 'undefined') {
        return window.fetch.bind(window);
    } else if (typeof self !== 'undefined') {
        return self.fetch.bind(self); // <------------ **it will fail here**
    } else if (typeof exports === 'object' && typeof module !== 'undefined') {
        return require('node-fetch');
    } else {
        throw new Error('Your environment is not defined');
}
```

**Comment by xenohunter** [comment]
Fixed in https://github.com/wavesplatform/waves-api/pull/35.

**Comment by xenohunter** [comment]
Published as `@waves/waves-api@0.24.5`.

**Comment by xenohunter** [comment]
Excuse me, it's published with the version `@waves/waves-api@0.24.6`.

**Comment by dananichev** [comment]
@xenohunter are you going to publish this on NPM also?

**Comment by dananichev** [comment]
@xenohunter oh, only now i noticed you changed package name. Sorry.

**Comment by xenohunter** [comment]
@dananichev it's alright. Thank you again for the contribution!
