### ISSUE TITLE
Interfaces import is broken in types

### ISSUE THREAD

**Issue by SvenSeemann** [wavesplatform/waves-api#44]
All imports of `interfaces.d.ts` in `raw/src/` are one folder level short.

e.g.
`raw/src/classes/Seed.d.ts`
```typescript
import { IKeyPair } from '../../interfaces';
// should be
import { IKeyPair } from '../../../interfaces';
```

Is there any reason to put `interfaces.d.ts` in the root path? 
I tried moving it to `src/` and everything works just fine. I can provide a pull request if this would be a viable solution.

**Comment by xenohunter** [comment]
Hello! Thank you for coming up with this. I'm sure we had no such issue. Do you use the the files from the _/dist_ directory? They are supposed to be the ones to use, not those from _/raw_ which are used only temporarily, for building purposes.

**Comment by SvenSeemann** [comment]
What I was tried to do was creating an angular app (run and build with angular-cli) using the waves-api module.

```
npm install waves-api
+ waves-api@0.24.2
```

With this dependency starting the app fails with errors for the used imports from waves-api.

```
ERROR in node_modules/waves-api/raw/src/WavesAPI.d.ts(1,37): error TS2307: Cannot find module '../interfaces'.

node_modules/waves-api/raw/src/api/matcher/index.d.ts(1,33): error TS2307: Cannot find module '../../../interfaces'.

node_modules/waves-api/raw/src/api/node/index.d.ts(1,78): error TS2307: Cannot find module '../../../interfaces'.

node_modules/waves-api/raw/src/classes/Seed.d.ts(1,26): error TS2307: Cannot find module '../../interfaces'.
```

I fixed the issue for me by using @waves/waves-api which seems to install a newer version without the issue.

```
npm install --save @waves/waves-api
+ @waves/waves-api@0.28.0
```

Maybe you could explain a bit more whats the difference between waves-api and @waves/waves-api (as running waves-api is used in README file).

**Comment by xenohunter** [comment]
It seems README.md needed an update. Done in https://github.com/wavesplatform/waves-api/commit/94c964a1955f560697b6bf2fa8a33426f16fdfab.
