### ISSUE TITLE
Mass Asset Transfer

### ISSUE THREAD

**Issue by putuyuwono** [wavesplatform/waves-api#49]
Hello, is there any plan to support Mass Asset transfer in near future?

**Comment by xenohunter** [comment]
Hello! It had been already done at the time you asked: https://github.com/wavesplatform/waves-api/commit/ea48140e8f60b7567ef46c59e03c497887ce186f.

**Comment by putuyuwono** [comment]
Nicely done! Is there any documentation on how to use mass-transfer?

**Comment by xenohunter** [comment]
Not yet, but it will be published quite soon. Right now you can rely on the schema of it (here, in the commit: https://github.com/wavesplatform/waves-api/commit/ea48140e8f60b7567ef46c59e03c497887ce186f#diff-52c767adfd0cda41b6f185351c8f80fcR5).
