### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by wandyer** [wavesplatform/waves-api#55]
Hey. I'm trying to build this project for testing and it's giving me some errors.

Commands that I'm executing: 
npm install
npm run build

Error:
![Image](https://cdn.pbrd.co/images/HoPASEj.png)

**Comment by wandyer** [comment]
The problem seems to be on this command:

`./node_modules/.bin/tsc -p ./tsconfig.json --declaration --outDir raw`

I'm on a Mac

**Comment by xenohunter** [comment]
Hello, and thanks for reporting! Could you please try to build again on the [newest version](https://www.npmjs.com/package/@waves/waves-api)?

**Comment by wandyer** [comment]
It works now. Thanks

**Comment by xenohunter** [comment]
Great!
