### ISSUE TITLE
Development on testNet

### ISSUE THREAD

**Issue by tamarcarmon** [wavesplatform/waves-api#56]
This is my first time trying to use the API. I created a token in testNet, When using Node.js to check the balance on that address i am getting wrong balance LOL. I created 5M tokens, but i get a balance of 9M.
Also using detailed balance i dont get balance by token symbols but only total.

**Comment by xenohunter** [comment]
Hello! Please, could you try it out again with the [newest version](https://www.npmjs.com/package/@waves/waves-api)?

**Comment by xenohunter** [comment]
Please, reopen if it's still of interest.
