### ISSUE TITLE
Node assets transfer method is missing

### ISSUE THREAD

**Issue by SvenSeemann** [wavesplatform/waves-api#60]
I tried creating a transaction with the current (v1.1.0) version as it is described in the Readme: https://github.com/wavesplatform/waves-api#transfer-transaction

```typescript
this._wavesApi.API.Node.assets.transfer(transferData, this.seed.keyPair);
```

But seems like the assets Object not having a transfer method. 
When checking the methods on the assets object it shows only three methods (also the types only define just these three methods):

```
assets: {
        balances(address: string): Promise<any>;
        balance(address: string, assetId: string): Promise<any>;
        distribution(assetId: string): Promise<any>;
};
```

**Comment by xenohunter** [comment]
Hello, Sven! Thanks for reaching out. All methods which create transactions are now merged into one, for transfer it'll be like: `Waves.API.Node.transactions.broadcast('transfer', transferData, keyPair)`.

**Comment by SvenSeemann** [comment]
I tried adding the transactions with `Waves.API.Node.transactions.broadcast` function. 
But this one creates a Version 2 Transaction which will be currently rejected by my development Waves Node (v0.13.4).

This is the error I get on the transaction broadcast request:
`
{
    "error": 112,
    "message": "State check failed. Reason: ActivationError(TransferTransactionV2 transaction has not been activated yet)",
     ...
}
`

As I can't modify the created transaction request and the "old" transfer method is missing, is there any way to create and broadcast an transaction with the latest version of the waves-api module?

**Comment by xenohunter** [comment]
Yeah, you are correct for sure. No, sadly there is no way right now but it's okay to use an older version.

Sorry for that inconvenience, we'll try to fix it and provide a tool to work with any transaction.

**Comment by SvenSeemann** [comment]
Thanks for the clarification. 

No problem, i can just use an older version for now. Keep up the good work!
If you need some support I would be happy to contribute something to help.

**Comment by Diegoescalonaro** [comment]
Could you finally create the transaction?

**Comment by xenohunter** [comment]
The transactions are temporarily back to their first versions. And the docs are updated.

**Comment by PhanPirang** [comment]
{ "error": 112, "message": "State check failed. Reason: ActivationError(TransferTransactionV2 transaction has not been activated yet)", ... }

I got this error message when I transfer token on MainNet. How to solve it?

**Comment by xenohunter** [comment]
@PhanPirang, try the newest version of waves-api. If the problem will persist please create a new issue.
