### ISSUE TITLE
Can't send transactions

### ISSUE THREAD

**Issue by fsanano** [wavesplatform/waves-api#62]
I think readme.md is outdated. 
`transfer` method does not exist.
```
Waves.API.Node.assets.transfer(transferData, seed.keyPair).then((responseData) => {
    console.log(responseData);
});
```

I try send transaction like this: 
```
const transferData = {
    recipient: 'addrs',
    assetId: 'WAVES',
    feeAssetId: 'WAVES',
    amount: 10 * 10**8,
    fee: 100000,
    attachment: '',
    timestamp: Date.now(),
}
Waves.API.Node.transactions.broadcast('transfer', transferData, keys);
```
but catch error `State check failed. Reason: Script doesn't exist and proof doesn't validate as signature for waves`

Can you fix readme.md and help me ?

**Comment by xenohunter** [comment]
Hello! Thanks for reporting, we'll update it soon.

Are you sure the keys relate to the right account?

**Comment by xenohunter** [comment]
Or maybe you're using mainnet keys on testnet or vice versa?

**Comment by fsanano** [comment]
I use correct keys and use testnet

**Comment by xenohunter** [comment]
Is `recipient: 'addrs'` really looks like this? With `'addrs'` string?

**Comment by xenohunter** [comment]
Hello. Is it resolved? If not, please share the full code indeed.

Have you tried it with different sender and recipient addresses?

**Comment by fsanano** [comment]
I use different addresses. It not resolved.

**Comment by unknownfix** [comment]
TypeError: Waves.API.Node.assets.transfer is not a function
`"@waves/waves-api": "^1.2.0"`

I can to use 
```
Waves.API.Node.assets.balance('3MxR25YCfw6tgZg22egVhrvHocfgtiVQKbr', 'WAVES').then((balance) => {
   console.log(balance);
});
```
```
But Waves.API.Node.assets.transfer return error **TypeError: Waves.API.Node.assets.transfer is not a function**
Waves.API.Node.assets.transfer(transferData, seed.keyPair).then((responseData) => {
    console.log(responseData);
});
```

@xenohunter can you help?

**Comment by unknownfix** [comment]
**SOLVED** . @xenohunter You moved transaction in broadcast section. Please update documentation asap.
Right call of method 
`Waves.API.Node.transactions.broadcast('transfer', transferData, seed.keyPair).then((responseData) => {
	console.log(responseData);
});`

**Comment by xenohunter** [comment]
@unknownfix thank you for the comment but @fsanano already used the right call.

Yes, we will update the docs very soon.

**Comment by Diegoescalonaro** [comment]
Solved?
