### ISSUE TITLE
Create signature

### ISSUE THREAD

**Issue by kelvinsinsua** [wavesplatform/waves-api#63]
Hi everybody,

Im a new developer into the waves-api, i need sign a transfer transaction and i dont know hoe obtain the signature value.

Exist any method to create the signature? or you can provideme a code or documentation example. 

Thanks to all, sorry for my bad english.

**Comment by xenohunter** [comment]
Hello! There is a different repo, [waves-signature-generator](https://github.com/wavesplatform/waves-signature-generator).

It is mostly self-documented, you can start with that file: https://github.com/wavesplatform/waves-signature-generator/blob/master/src/signatureFactory/SignatureFactory.ts.

**Comment by Diegoescalonaro** [comment]
@kelvinsinsua could you create the signature?
