### ISSUE TITLE
Error on create seed at nodejs

### ISSUE THREAD

**Issue by marcelomorgado** [wavesplatform/waves-api#69]
```
var WavesAPI = require('@waves/waves-api');
const Waves = WavesAPI.create(WavesAPI.TESTNET_CONFIG);

const seed = Waves.Seed.create();
console.log(seed);

```
(function (exports, require, module, __filename, __dirname) { (function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.WavesAPI=f()}})(function(){var define,module,exports;return function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}({1:[function(require,module,exports){(function(process,global){(function(

**Error: Secure random number generation is not supported by this browser.
Use Chrome, Firefox or Internet Explorer 11**
    at Object.oldBrowser (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:547277)
    at nodeRandom (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:65661)
    at secureRandom (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:66655)
    at Object.randomUint8Array (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:66886)
    at Object.generateRandomUint32Array (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:89347)
    at Function._generateNewSeed (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:3922)
    at Function.create (/home/cmarcelo/git/waves2/node_modules/@waves/waves-api/dist/waves-api.min.js:1:3350)
    at Object.<anonymous> (/home/cmarcelo/git/waves2/test.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)

**Comment by marcelomorgado** [comment]
Same error occurs when function tx.addProof(privKey) is called

**Comment by xenohunter** [comment]
Hello! Could you please specify, in which browser do you encounter that error?

**Comment by marcelomorgado** [comment]
Hi, I'm using nodejs command line (linux bash).

**Comment by xperiafan13-rom** [comment]
some error, using firefox lasted version

**Comment by unknownfix** [comment]
Same error.
Nodejs version 8 command line
Waves api version 1.3.0

**Comment by tiranid99** [comment]
I have same error on api 1.3.0, node version 10.3

**Comment by xenohunter** [comment]
Thanks to all of you, the issue is with the build process, we'll fix that soon.

**Comment by tiranid99** [comment]
@flute use 1.0 or 1.1 version. It works for me

**Comment by hfucek** [comment]
for nodejs users:

make file waves-api.js:

```
var WavesAPI = require('@waves/waves-api');
var crypto = require('crypto');

global.crypto = {
  getRandomValues: function(rawBytes) {
    return crypto.randomBytes(rawBytes.length);
  }
};

module.exports = WavesAPI;

```


then include it as

`var WavesAPI=require("waves-api");`

that should make a trick...

**Comment by hfucek** [comment]
for nodejs developers:

create waves-api.js:

```
var WavesAPI = require('@waves/waves-api');
var crypto = require('crypto');

global.crypto = {
  getRandomValues: function(buffer) {
   crypto.randomFill(buffer, function(err, buf){
      if (err) throw err;
     });
  }
};

module.exports = WavesAPI;

```

use it as:

```
var WavesAPI = require('./waves-api');
const Waves = WavesAPI.create(WavesAPI.TESTNET_CONFIG);

const seed = Waves.Seed.create();
console.log(seed);

```

**Comment by xenohunter** [comment]
@hfucek, thank you for providing a workaround!

**Comment by xenohunter** [comment]
We fixed that bug. Starting with [version 1.5.0](https://github.com/wavesplatform/waves-api/releases/tag/1.5.0), everything will work fine.
