### ISSUE TITLE
Can't send transaction

### ISSUE THREAD

**Issue by Diegoescalonaro** [wavesplatform/waves-api#70]
>   "error": 112,
>   "message": "State check failed. Reason: Script doesn't exist and proof doesn't validate as signature for

So, when will it be solved?

**Comment by Diegoescalonaro** [comment]
> The requested resource could not be found but may be available again in the future.

So, it's impossible to make a transfer via API?

**Comment by unknownfix** [comment]
check that section https://github.com/wavesplatform/waves-api#transfer-transaction
works well for waves and asset transactions

**Comment by Diegoescalonaro** [comment]
@unknownfix  Yes... I tried that, but didn't work...

>   "error": 112,
>   "message": "State check failed. Reason: ActivationError(TransferTransactionV2 transaction has not been activated yet)",
>

**Comment by unknownfix** [comment]
So, you can try to kick @xenohunter for do working api. Or kick off that api and use [node rest api](https://docs.wavesplatform.com/en/development-and-api/waves-node-rest-api.html) and [sign transaction](https://docs.wavesplatform.com/en/technical-details/cryptographic-practical-details.html) by your hands and

**Comment by xenohunter** [comment]
Hello! Sorry for a gross inconvenience, transaction sending is fixed in [1.4.0](https://github.com/wavesplatform/waves-api/releases/tag/1.4.0).
