### ISSUE TITLE
State check failed. Reason: Script doesn't exist and proof doesn't validate as signature

### ISSUE THREAD

**Issue by unknownfix** [wavesplatform/waves-api#73]
API version 1.2.0
`const Waves = WavesAPI.create(WavesAPI.TESTNET_CONFIG);
  const seed = Waves.Seed.fromExistingPhrase(TEST_PHRASE);

  const sponsorshipData = {
    assetId: TEST_ASSET,
    minSponsoredAssetFee: 100000,
    fee: 100000000,
    timestamp: Date.now()
  };

  Waves.API.Node.transactions.broadcast('sponsorship', sponsorshipData, seed.keyPair).then((responseData) => {
    res.json(responseData);
  }).catch((responseData) => {
    res.json(responseData);
  });`

`
  "name": "WavesRequestError",
  "data": {
    "error": 112,
    "message": "State check failed. Reason: Script doesn't exist and proof doesn't validate as signature for {\"type\":14,\"id\":\"HCdDxM4jH53nN32rANx9A3HVJ5rgkyVTgvbcBzLCqKTR\",\"sender\":\"3N9atHZUYJ14qvoGeLyucmhMnNRSiRL7Sno\",\"senderPublicKey\":\"2ard3BP4uEC5WqXA4hZaHfTcVcS3BCupv1LNsTwYxFZc\",\"fee\":100000000,\"timestamp\":1532597309342,\"proofs\":[\"4VepyLbQtVz5xgXX5rW5Sxg2vgn42YfdLy4MwX6m593hUZyYmfPzvapcJL24SJHRv42nobYtkgsg2gu3rSXn6qKT\"],\"version\":1,\"assetId\":\"8BF1ZmmMXRnURxPDoz1QqMpWBWQxrqQHKBQvgt5j5eVT\",\"minSponsoredAssetFee\":100000}",
    "tx": {
      "type": 14,
      "id": "HCdDxM4jH53nN32rANx9A3HVJ5rgkyVTgvbcBzLCqKTR",
      "sender": "3N9atHZUYJ14qvoGeLyucmhMnNRSiRL7Sno",
      "senderPublicKey": "2ard3BP4uEC5WqXA4hZaHfTcVcS3BCupv1LNsTwYxFZc",
      "fee": 100000000,
      "timestamp": 1532597309342,
      "proofs": [
        "4VepyLbQtVz5xgXX5rW5Sxg2vgn42YfdLy4MwX6m593hUZyYmfPzvapcJL24SJHRv42nobYtkgsg2gu3rSXn6qKT"
      ],
      "version": 1,
      "assetId": "8BF1ZmmMXRnURxPDoz1QqMpWBWQxrqQHKBQvgt5j5eVT",
      "minSponsoredAssetFee": 100000
    }
  }
}`

**Comment by xenohunter** [comment]
Hello! Sorry for the inconvenience, transaction sending is fixed in [1.4.0](https://github.com/wavesplatform/waves-api/releases/tag/1.4.0).
