### ISSUE TITLE
1.3.0 Any transaction return empty response

### ISSUE THREAD

**Issue by unknownfix** [wavesplatform/waves-api#74]
API version 1.3.0
for example `Waves.API.Node.transactions.broadcast('transfer', transferData, seed.keyPair).then((responseData) => {
    res.json(responseData);
  })`

**Comment by xenohunter** [comment]
Hello! Thanks for reporting, and sorry for the inconvenience, transaction sending is fixed in [1.4.0](https://github.com/wavesplatform/waves-api/releases/tag/1.4.0).

**Comment by unknownfix** [comment]
API version 1.4.0
Still have empty response and transaction is not executed @xenohunter
