### ISSUE TITLE
Still have empty response and transaction is not executed

### ISSUE THREAD

**Issue by unknownfix** [wavesplatform/waves-api#75]
API version 1.4.0
Still have empty response and transaction is not executed

**Comment by xenohunter** [comment]
Hello! Could you please attach logs? Or maybe any errors in the console?

**Comment by unknownfix** [comment]
first request 200
second request 304
third request 304
fourth request 200
or any random sequence
no one error

**Comment by xenohunter** [comment]
I would say those random faults are the issue on the Node side, or a connectivity one.
Please, try to ask in the [Node repository](https://github.com/wavesplatform/Waves).
