### ISSUE TITLE
Error while transfer assets via Waves.API.Node.transactions.broadcast('transfer', ...)

### ISSUE THREAD

**Issue by tiranid99** [wavesplatform/waves-api#76]
Hello, 

I want send assets, and I used 1.0 and 1.1 version for it and received error **"State check failed. Reason: ActivationError(TransferTransactionV2 transaction has not been activated yet)"** 

Also I tried send assets on api versions 1.3 and 1.4 and I get error **"Secure random number generation is not supported by this browser"**. I get this error on almost any interaction with api using 1.3/1.4 versions. 

Please help with that, I really need working method to send assets to another address.

Screens of errors (1.0/1.1 and 1.3/1.4) and my transfer code are listed below.
![image](https://user-images.githubusercontent.com/18747731/43717876-98985bfe-9991-11e8-8aaa-8a55d3b9fcb7.png)

![image](https://user-images.githubusercontent.com/18747731/43717893-a72e0c36-9991-11e8-833b-50ef0f4598dd.png)

![image](https://user-images.githubusercontent.com/18747731/43717898-ac29bca8-9991-11e8-90c0-8505b1ddcfd9.png)

**Comment by xenohunter** [comment]
Hello, and thanks for reporting. You can checkout to a commit with the version 1.1, change the version of _waves-signature-generator_ to 0.14.0, and then run `npm i` and build the library.
