### ISSUE TITLE
Bad arguments

### ISSUE THREAD

**Issue by krboktv** [wavesplatform/waves-api#77]
[Link1](https://github.com/wavesplatform/waves-api/blob/master/src/api/matcher/info.ts)

```
import { createFetchWrapper, PRODUCTS, VERSIONS, processJSON } from '../../utils/request';


const fetch = createFetchWrapper(PRODUCTS.MATCHER, VERSIONS.V1, processJSON);


export default {

    getMatcherKey() {
        return fetch('/');
    }

};
```

Should be: ```return fetch('/matcher');```

#### OR
[Link2](https://github.com/wavesplatform/waves-api/blob/master/src/constants.ts)

```matcherAddress: 'https://matcher.wavesplatform.com'```

Should be: ```matcherAddress: 'https://matcher.wavesplatform.com/matcher'```

**Comment by xenohunter** [comment]
Thank you for reporting that and sorry for the long delay. Fixed in https://github.com/wavesplatform/waves-api/commit/a2a23d02dcf97e532a6ee93dc2b31fd0ea1a2ae0.
