### ISSUE TITLE
Where is Waves.crypto.isValidTransactionSignature()?

### ISSUE THREAD

**Issue by chelahmy** [wavesplatform/waves-api#82]
In [Waves Auth API](https://docs.wavesplatform.com/en/development-and-api/client-api/auth-api.html) we were informed that the returned signature can be verified using the Waves.crypto.isValidTransactionSignature() function. But the function seems missing from the API. I have checked it with the latest package using [npm runkit with @waves/waves-api](https://npm.runkit.com/@waves/waves-api).

At least an algorithm to verify the signature will be helpful.

**Comment by chelahmy** [comment]
I traced the codes in the @waves/waves-api to figure out how the signing were done in the first place. The codes implemented a lot of promises and adapters so I have to do a lot of guessing works. After plenty of trials and errors here is how I verify the signature:

~~~javascript
const WSG = require("@waves/waves-signature-generator")

function auth_verify(public_key, signature, host, data) {
	var w = WSG.utils.convert.stringToByteArrayWithSize("WavesWalletAuthentication");
	var h = WSG.utils.convert.stringToByteArrayWithSize(host);
	var d = WSG.utils.convert.stringToByteArrayWithSize(data);

	var m = WSG.utils.concatUint8Arrays.apply(void 0, [Uint8Array.from(w), Uint8Array.from(h), Uint8Array.from(d)]);

	var s = WSG.libs.base58.decode(signature);
	var p = WSG.libs.base58.decode(public_key);

	return WSG.libs.axlsign.verify(p, m, s);
}

var public_key ="4GhinWrfkJrLqtgNvLdNZipN2Ha92Z9W3Y1JBo8TLrcf";
var signature = "218WL5u3gP7eE2t2ffpsYpLkyCtK143BbtNY7bHTRDSnGUdzXTjhawBiF9sUoVZwTS61jZbC1Qi7U2xKUDQBJw2F";
var host ="answering.cryptobubbles.club";
var data = "0123456789";

auth_verify(public_key, signature, host, data);
~~~

Here are some points:
1. The signing were done using axlsign.sign(). So, it will have to be verified using axlsign.verify().
2. There are three strings packed together as the message to be signed: i) "WavesWalletAuthentication", ii) the referrer host, and iii) the referrer data.
3. Each string above have to be converted to byte-array-with-length before being packed together. The length of a string is kept in a two bytes big-endian preceding the string.
4. Only the domain name is taken from the referrer host. Without the http:// and the slashes.
5. The signed message will have to be repacked for verification with axlsign.verify().
6. The public key and the signature need to be decoded from base58 before passing them to axlsign.verify().

**Comment by chelahmy** [comment]
PHP version: [https://github.com/chelahmy/waves_auth](https://github.com/chelahmy/waves_auth)

**Comment by xenohunter** [comment]
Thank you for your contribution! The method's been renamed, it's `Waves.crypto.isValidSignature()` now.

**Comment by xenohunter** [comment]
I also fixed in in the docs: https://github.com/wavesplatform/waves-documentation/commit/b4716b99e66578b651831545daa85c90da032f51.
